### ISSUE TITLE
Suggestion: Possibility to add roles according to some Minecraft Placeholders

### ISSUE THREAD

**Issue by Louwiiii** [DiscordSRV/DiscordSRV#1116] opened 2021-05-09 14:07 UTC
In my exemple, I would like to add a Discord role to players who are members of a Towny Nation (the name of the role would be the nation's name).

**Comment by Vankka** [comment] 2021-05-09 20:18
Closing as a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/921, having roles for towns is planned

**Closed by Vankka** 2021-05-09 20:18 UTC
