### ISSUE TITLE
ChannelUpdater with alternative embeds 

### ISSUE THREAD

**Issue by ofunny** [DiscordSRV/DiscordSRV#1461] opened 2022-09-21 03:10 UTC
### Why?

The new ChannelUpdater feature is nice but will only update a channels name. If you have more than one server in your network you would need one channel each. 

### What and How?

It would be cool if you could alternatively use embeds what will be sent to the same channel and updated on  UpdateInterval – so you could create a dedicated read only channel containing one embed per server showing the data you wanna show.

### Are there alternatives?

---

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment] 2022-09-21 03:25
duplicate of #1251

**Closed by granny** 2022-09-21 03:25 UTC
Labels: enhancement
