### ISSUE TITLE
Updating does resets some configs

### ISSUE THREAD

**Issue by Armoured-Monkey** [DiscordSRV/DiscordSRV#966] opened 2021-01-09 16:26 UTC
Whenever I have updated the plugin, parts or all of linking.yml get reset. This is mainly noticeable by the first setting.

Require linked account to play: 
  Enabled: true

gets reset to

Require linked account to play: 
  Enabled: false

This breaks the security of the server, and should not happen.

**Comment by Vankka** [comment] 2021-01-09 16:31
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/212

**Closed by Vankka** 2021-01-09 16:31 UTC
