### ISSUE TITLE
Feature Request: Pass AFK status from Essentials X

### ISSUE THREAD

**Issue by KenaiTheWolf** [DiscordSRV/DiscordSRV#887] opened 2020-10-21 16:49 UTC
Pass AFK status from Essentials X to the discord chat, such that discord users would see a webhook (if enabled) similar to bellow:

System Message:
> %playername is now AFK

This would allow players to know when a user is automatically marked AFK by the server.

**Comment by BlueTree242** [comment] 2020-10-21 18:31
I have made my own addon to do that, and it works. All you need is to code it, if you cant, please wait till i release it.

**Comment by Vankka** [comment] 2020-10-21 18:32
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/345

**Closed by Vankka** 2020-10-21 18:32 UTC

**Comment by KenaiTheWolf** [comment] 2020-10-21 18:34
> I have made my own addon to do that, and it works. All you need is to code it, if you cant, please wait till i release it.

I can program it, just don't have time at the moment. I've put code changes made by myself to my server on hiatus till December because... I don't have time to put out any fires I start by mistake so to speak.
