### ISSUE TITLE
Vanish Improvement

### ISSUE THREAD

**Issue by Bbro122** [DiscordSRV/DiscordSRV#956] opened 2020-12-31 16:55 UTC
So I understand that DiscordSRV blocks join/leave when a vanished player joins the server

However from what I've seen it only does that when the player joins or leaves the server and doesn't do it for when someone actually enters or exits vanish (unless I'm just stupid and didn't see something)

So what this means is if a staff goes into vanish and a leave message isn't sent to public logs it would be very easy to tell they went into vanish and never actually left

**Comment by Vankka** [comment] 2020-12-31 17:14
This is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/220, plugins like SuperVanish don't have the right events for us to be able to do this, and thus it's up to them to. SuperVanish is just a very common example, but this applies to other plugins as well, as many don't have the right events.

**Closed by Vankka** 2020-12-31 17:14 UTC
