### ISSUE TITLE
Unlock command?

### ISSUE THREAD

**Issue by Blueeyestar** [DiscordSRV/DiscordSRV#695] opened 2020-04-21 11:34 UTC
since we do not have to give every player in discord the rank of players that are unlocked by us manually.

Is it possible to give the player in discord a rank with a command in the game? or is that not technically possible?

With us, players from 50 hours playing time become regular regular players and are thus automatically unlocked in many ways. Is this also possible with discord ranks?

**Comment by Vankka** [comment] 2020-04-21 22:09
No it is not possible to *directly* give a (player's linked) user a role, but you can do this using group sync & your permissions plugin (if I understood this correctly)

**Comment by Vankka** [comment] 2020-05-21 21:23
From what it seems you could use group synchronization to achieve this (if I understood it right). But never the less adding/removing roles using commands is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/331

**Closed by Vankka** 2020-05-21 21:23 UTC
