### ISSUE TITLE
Discord Rich Presence Integration

### ISSUE THREAD

**Issue by patrickh39** [DiscordSRV/DiscordSRV#793] opened 2020-07-11 23:50 UTC
Hi there, I’m wondering if it’s possible to integrate the Discord bot with the server’s status. By that I mean, everytime somebody leaves or joins, clicking on the bot would show the amount of players online, and the server status. I know that this is already a thing when you go to the global server chat channel, but that does not update really quickly, it updates every 5-10 mins for me. 

What I’m talking about looks a little like this:
![8208C1B3-BAE4-4AB9-B7D9-6956359F7D82](https://user-images.githubusercontent.com/61527626/87235909-9f19cb80-c396-11ea-89d6-035242149e0c.png)

**Comment by Vankka** [comment] 2020-07-12 00:18
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/300. Bot's can't use rich presence as of now

**Closed by Vankka** 2020-07-12 00:18 UTC
