### ISSUE TITLE
Enhancement: Emoji substitution and filtering

### ISSUE THREAD

**Issue by metalshark** [DiscordSRV/DiscordSRV#623] opened 2020-02-04 08:48 UTC
Could an option be added for configuring a mapping of emojis in DiscordToMinecraft messages to substitute text something like:

`DiscordChatEmojiTranslations: {
  ":smile:": ":-)",
}`

then a boolean option to filter or keep those not translated?

**Comment by pkrok01** [comment] 2020-02-04 08:57
Similar/Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/549#issuecomment-539153473

Recommend using [EmojiChat](https://github.com/RadBuilder/EmojiChat) to process emojis if that's of interest 
(Requires a resource pack to be applied for emojis to be viewable in-game)

**Closed by pkrok01** 2020-02-04 08:57 UTC
