### ISSUE TITLE
send message in threads

### ISSUE THREAD

**Issue by HeroLeam** [DiscordSRV/DiscordSRV#1620] opened 2024-01-05 17:04 UTC
### Why?

for example log messages, I can have a text channel on discord to talk only about minecraft, and within that text channel I can create a "logs" topic for it to send login messages, achievements, etc.

### What and How?

for example log messages, I can have a text channel on discord to talk only about minecraft, and within that text channel I can create a "logs" topic for it to send login messages, achievements, etc.

### Are there alternatives?

At the moment there is no alternative

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment] 2024-01-05 19:07
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1217

**Closed by Vankka** 2024-01-05 19:07 UTC
Labels: enhancement
