### ISSUE TITLE
when turned off the server while it is disabling the plugin.

### ISSUE THREAD

**Issue by comonier** [DiscordSRV/DiscordSRV#1505] opened 2023-02-26 13:48 UTC
### Expected behavior

There is no problem here, just reporting that console ERROR when i turned off the server

but i think this is due to another bot plugin i have JDA plugin from Fabiozumbi12 UltimateChatBot.
so i would just like to know if that could be it

![image](https://user-images.githubusercontent.com/19571541/221414439-a3a5d257-a2c3-4671-8b38-ce8ac7aa9820.png)

### Actual behavior

```yaml
[00:13:29] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: null
[00:13:29] [pool-78-thread-1/WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: -1: java.io.InterruptedIOException
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:249)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:13:29] [pool-78-thread-1/WARN]: Caused by: java.io.InterruptedIOException
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:641)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:148)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:137)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:93)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:201)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:141)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:124)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[00:13:29] [pool-78-thread-1/WARN]: 	... 3 more
[00:13:29] [pool-78-thread-1/WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:249)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[00:13:29] [pool-78-thread-1/WARN]: 	at DiscordSRV-1.26.1.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[00:13:29] [pool-78-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[00:13:29] [pool-78-thread-1/WARN]: 	... 3 more
[00:13:29] [DiscordSRV - Shutdown/INFO]: [DiscordSRV] Shutdown completed in 537ms
```

### Steps to reproduce

Just turned server off

### Server software and version

Paper version git-Paper-417

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

it's working fine - 
this does not affect absolutely anything, I just decided to report it out of curiosity
about what could be the reason for him reporting this to me when hanging up

**Comment by Vankka** [comment] 2023-02-26 14:06
This is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1466

**Closed by Vankka** 2023-02-26 14:06 UTC
Labels: bug
