### ISSUE TITLE
Add ability to parse offline player placeholders

### ISSUE THREAD

**Issue by Insprill** [DiscordSRV/DiscordSRV#938] opened 2020-12-17 06:37 UTC
I would love to see the ability to parse placeholders for offline players. I wrote some custom PAPI placeholders for offline players except DiscordSRV won't parse them haha. Specifically for `DiscordToMinecraftChatMessageFormat` in the `messages.yml`.

**Comment by Vankka** [comment] 2020-12-18 16:36
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/904

**Closed by Vankka** 2020-12-18 16:36 UTC
