### ISSUE TITLE
Possibillity to allow multiple MC-accounts to a single discord account

### ISSUE THREAD

**Issue by Lorias-Jak** [DiscordSRV/DiscordSRV#1712] opened 2024-06-30 20:05 UTC
### Why?

It often happens that a Minecraft server allows users to have multiple MC accounts playing. However, you can currently only link one account per discord account. To unlock certain features ingame it would be helpful if users could link one Discord account to several MC accounts, not limited to one.

### What and How?

* the `/discordsrv link` command allows to connect multiple minecraft accounts to a single discord user. 
* a config option to set a maximum for accounts. 

### Are there alternatives?

None I'm aware of atm

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment] 2024-07-07 10:38
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1308

**Closed by Vankka** 2024-07-07 10:38 UTC
Labels: enhancement
