### ISSUE TITLE
Use Minecraft username for Discord -> MC when accounts are linked

### ISSUE THREAD

**Issue by jordanwilliams1** [DiscordSRV/DiscordSRV#472] opened 2019-05-25 09:06 UTC
Make it possible so when you type in discord it will show your Minecraft accounts username in-game instead of your discord name. 

Some peoples discord names are really really different from there minecraft username.. making people get confused in-game.

**Comment by jordanwilliams1** [comment] 2019-06-06 12:36
@Scarsz Could you please add this :(? It's the only thing holding me back from adding it to my server

**Comment by Disorbs** [comment] 2019-06-10 20:15
i second this pls add variable like %mc-username% to use their raw mc name so they can use nicknames in their discord but still output to minecraft with their name. :)

**Comment by Andre601** [comment] 2019-06-10 23:56
An option you already have right now is enabling the setting to set the nickname of the User in Discord to their ingame name and then just use `%username%` as this uses their displayname if set.

**Comment by granny** [comment] 2020-10-06 11:06
Duplicate of #418

**Closed by granny** 2020-10-06 11:06 UTC
Labels: enhancement

**Comment by Harsh-7821** [comment] 2022-07-22 14:30
how can i do that? i have seen many minecraft servers doing that but i am unable to find anything related to it pls reply
