### ISSUE TITLE
PremiumVanish

### ISSUE THREAD

**Issue by untuned** [DiscordSRV/DiscordSRV#665] opened 2020-03-20 23:27 UTC
You hook into SuperVanish, however when using PremiumVanish the "player left the server" message doesn't appear.

**Comment by Vankka** [comment] 2020-03-20 23:28
Fake join or leave messages are implemeneted.

Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/220

**Closed by Vankka** 2020-03-20 23:28 UTC
