### ISSUE TITLE
Emoji converted to text in message format

### ISSUE THREAD

**Issue by Katrix** [DiscordSRV/DiscordSRV#634] opened 2020-02-14 22:54 UTC
Currently all emojis in the message sent to minecraft are converted to their text counterpart. We want to use an emoji that minecraft supports in the `DiscordToMinecraftChatMessageFormat` and `DiscordToMinecraftChatMessageFormatNoRole` fields, but we can't. Would it be possible to only apply the conversion to the contents of the message sent from Discord, and not everything in the formatted message?

**Comment by Vankka** [comment] 2020-02-17 20:52
Emojis can be *disabled* in Discord -> Minecraft messages by setting `ParseEmojisToNames` to `false`, in latest dev builds (https://snapshot.discordsrv.com)
However Minecraft doesn't really support unicode characters in the range that emojis are, the next best thing would be a plugin like EmojiChat (supports DiscordSRV) that adds support for them by *replacing* Korean/Chinese characters with emojis using resource packs (https://www.spigotmc.org/resources/emojichat.50955/)

Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/507

**Closed by Vankka** 2020-02-17 20:52 UTC

**Comment by Katrix** [comment] 2020-02-17 21:00
I don't want to disable emoji's. While Minecraft doesn't support most Emojis, it does support the one we want to use just fine. Our chat looks stupid as it is currently because we're substituting the emoji for a simple `O`. If the server admin put the emoji in the config, isn't it on them to know that Minecraft will support it? 

In our case it's the yin yang emoji, which displays just fine in minecraft.
![image](https://user-images.githubusercontent.com/11007080/74686182-939bed00-51c8-11ea-8703-444e61f93bb9.png)

**Comment by Vankka** [comment] 2020-02-17 21:03
See Issue #507 in that case
