### ISSUE TITLE
Configuration files are reset EVERY update

### ISSUE THREAD

**Issue by Brawaru** [DiscordSRV/DiscordSRV#947] opened 2020-12-25 11:50 UTC
Hello! I noticed that whenever the plugin gets updated, all of the configuration files get incorrectly migrated, resulting in half settings being reset to defaults.

One of the examples is messages file — the only preserved lines are prefixes, all the messages, however, are reset to default values, while there are NO CHANGES in the file structure itself.

Is there anything that can be done about this? This is very counterproductive and makes me want to avoid any further updates and stick to certain version instead.

**Comment by Vankka** [comment] 2020-12-25 14:43
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/212

**Closed by Vankka** 2020-12-25 14:43 UTC
