### ISSUE TITLE
New error. Spamming 429 on console

### ISSUE THREAD

**Issue by DiegoDaniel** [DiscordSRV/DiscordSRV#722] opened 2020-05-30 02:44 UTC
[05:40:19] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/694765349567987723
[05:40:20] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/694765349567987723
[05:40:20] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/694765349567987723
[05:40:20] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/694765349567987723
[05:40:20] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/694765349567987723

**Comment by Scarsz** [comment] 2020-05-30 02:46
duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/719

**Closed by Scarsz** 2020-05-30 02:46 UTC
