### ISSUE TITLE
DiscordCannedResponses | & is replaced How to deal with it?

### ISSUE THREAD

**Issue by BearLeonLight** [DiscordSRV/DiscordSRV#535] opened 2019-08-23 15:31 UTC
I want to mark the group but & is replaced How to deal with it?
DiscordCannedResponses: {"!ip": "%server_tps%", "!buildserver": " <@&584145252286201876> <@&606515786550607894>"}
DC display<@584145252286201876> <@606515786550607894>

**Comment by Andre601** [comment] 2020-01-06 08:53
I think this is caused by DiscordSRV (somehow) translating color codes, even tho it shouldn't here... So there isn't a workaround right now.

**Comment by pkrok01** [comment] 2020-01-06 08:58
fixed in https://github.com/DiscordSRV/DiscordSRV/commit/a6288df25a342524c7cec99a70a39b2f949ca2e1#diff-8faa8203627875ee5a6670656303a8a1R27-R42

**Closed by pkrok01** 2020-01-06 08:58 UTC

**Comment by Andre601** [comment] 2020-01-06 09:04
Should perhaps also be reportet to PlaceholderAPI itself as I think this shouldn't be seen as an intentional behaviour.
