### ISSUE TITLE
Role aliases

### ISSUE THREAD

**Issue by ghost** [DiscordSRV/DiscordSRV#549] opened 2019-10-07 17:56 UTC
Hey there.
On our discord server we have roles which are using another font to look a bit better. For this suggestion I'd like to use the example role: "𝔇𝔢𝔳𝔢𝔩𝔬𝔭𝔢𝔯". 

So, Minecraft supports quite a few type of fonts but it's still rather limited. Especially fonts which would look cool on discord can not be used because the game will make them show as unknown letters. (A ? like sign.) My idea was to create an alias like thing. It'd work just like the colour link such as `DiscordChatChannelColorTranslations: {
  "99AAB5": "&f",
  "17ac86": "&3",
` etc. So for example:
`DiscordChatRoleNameTranslations: {
  "𝔇𝔢𝔳𝔢𝔩𝔬𝔭𝔢𝔯": "Developer",
  "𝔇𝔢𝔳𝔢𝔩𝔬𝔭𝔢𝔯1": "Developer1"` etc.

**Comment by pkrok01** [comment] 2019-10-07 18:52
To add on to this idea, but guiding it to an already accessible feature:
Improve upon ChannelRegex to have multiple pairs of regex.
["regex1":"replacement1","regex2":"replacement2"]

**Comment by Vankka** [comment] 2019-10-13 14:41
could be considered a duplicate of #339 but could also be implemented as a separate feature for PlaceholderAPI, for example (that wouldn't go through any regex processing)

**Comment by Scarsz** [comment] 2021-06-07 23:16
Implemented

**Closed by Scarsz** 2021-06-07 23:16 UTC
Labels: enhancement
