### ISSUE TITLE
MinecraftChatToDiscordMessageFormat %world% placeholder does not work anymore

### ISSUE THREAD

**Issue by uncovery** [DiscordSRV/DiscordSRV#751] opened 2020-06-08 06:29 UTC
Hi, I updated to the latest version and the %world% placeholder stopped working.

I am using multiverse, venturechat, placeholderAPI and tried all of the 

%world%
%worldalias%
%player_world% (which works in the normal chat)

Anyhow until the last update, %world% worked fine. %displayname% and %message% work fine as well. Only %world% gets shown as-is: 

>  uncovery (%world%):  test

My config:
```
MinecraftChatToDiscordMessageFormat: "**%displayname%** (%world%): %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "**%displayname%** (%world%): %message%"

```

**Comment by Vankka** [comment] 2020-06-08 14:19
This is to do with the new Venture Bungee hook, next version will not default to it, in the meantime you can add `VentureChat-Bungee` to `DisabledPluginHooks`

**Comment by uncovery** [comment] 2020-06-09 04:54
Thanks for the advice, I set

DisabledPluginHooks: ["VentureChat-Bungee"]

in config.yml but it still won't accept any of the 3 terms %world%, %worldalias%, %player_world% 

Anything else I could be doing wrong?
Upgraded placeholderAPI to the latest version today.

**Comment by Vankka** [comment] 2020-06-09 12:11
update to dev builds, https://snapshot.discordsrv.com

**Comment by Vankka** [comment] 2020-06-09 20:33
Not a bug & is fixed by disabling VentureChat bungee functionality on snapshots

**Closed by Vankka** 2020-06-09 20:33 UTC
