### ISSUE TITLE
Request: displayname of linked accounts placeholder

### ISSUE THREAD

**Issue by r3dmc** [DiscordSRV/DiscordSRV#576] opened 2019-11-22 21:52 UTC
I forced my players to link their accounts to use chat at discord chat channel of my server. I want to show their displaynames when they are chatting from discord. Because my displaynames contains their Land name, so when they send text from Discord everyone will be able to see their Land name like sent in-game.

**Comment by Vankka** [comment] 2019-11-23 10:25
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/227

**Closed by Vankka** 2019-11-23 10:25 UTC
