### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by WindupYT** [DiscordSRV/DiscordSRV#1325] opened 2021-12-10 20:21 UTC
### Why?

Hello!

I currently run a BungeeCord server, and would love to integrate with discord. However, I don't want to put DiscordSRV in every server, and would rather just to put it in bungee.

### What and How?

It should link to every server if I put it in the bungeecord server.

### Are there alternatives?

Well, no.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment] 2021-12-10 20:22
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/34

**Closed by Vankka** 2021-12-10 20:22 UTC
Labels: enhancement

**Comment by WindupYT** [comment] 2021-12-10 20:23
This is a duplicate of #34 which was never implemented. So i'm trying to make it stand out so you could implement it, as a server owner it's hard to put it in every server.

**Comment by Dinty1** [comment] 2021-12-10 20:24
It is being worked on. https://github.com/DiscordSRV/Ascension

**Comment by Dinty1** [comment] 2024-11-23 10:46
Unlike GTA6 you’re more than welcome to help make it happen faster…
