### ISSUE TITLE
Set channel for first join messages

### ISSUE THREAD

**Issue by ToodaLew** [DiscordSRV/DiscordSRV#1389] opened 2022-04-10 00:14 UTC
### Why?

I feel it would be beneficial to server staff/owners if they could have a set channel for user join messages so they can keep track of who has joined and when. 

### What and How?

If the config gives an option to set the channel that all first join messages are sent to as well as still allowing customer messages

### Are there alternatives?

Anyway the first join messages would be kept separate from the chat 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment] 2024-06-24 23:39
This is actually a duplicate of #1046. Seems reasonably straightforward though so I might try get it done soon (albeit a few years late 🙂)

**Closed by Dinty1** 2024-06-24 23:39 UTC
Labels: enhancement, good first issue
