### ISSUE TITLE
InterruptedException / ChannelLoggingHandler  - Disabling DiscordSRV

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1695] opened 2024-06-18 17:59 UTC
### Expected behavior

Proper server stop without warnings/errors.

### Actual behavior

```
[13:53:34] [Server thread/INFO]: [DiscordSRV] Disabling DiscordSRV v1.28.0-SNAPSHOT
[13:53:35] [pool-98-thread-1/WARN]: java.lang.RuntimeException: java.lang.InterruptedException
[13:53:35] [pool-98-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:271)
[13:53:35] [pool-98-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:146)
[13:53:35] [pool-98-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:57)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[13:53:35] [pool-98-thread-1/WARN]: Caused by: java.lang.InterruptedException
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:53:35] [pool-98-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:53:35] [pool-98-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:262)
[13:53:35] [pool-98-thread-1/WARN]: 	... 8 more
```

### Steps to reproduce

Stop server.

### Server software and version

Paper version 1.20.6-147-ver/1.20.6@e41d44f

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

Using DiscordSRV dev branch compiled against: https://github.com/DiscordSRV/DiscordSRV/commit/d4b27cccfe4318f7a8b887ee3adcd478c583e305

**Comment by Vankka** [comment] 2024-07-05 14:40
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1466

**Closed by Vankka** 2024-07-05 14:40 UTC
Labels: bug
