### ISSUE TITLE
Account links aren't updated to other servers instantly

### ISSUE THREAD

**Issue by NoltoxGit** [DiscordSRV/DiscordSRV#1697] opened 2024-06-22 10:24 UTC
### Expected behavior

There is no delay between the different servers.

### Actual behavior

There is a delay between one server and the others.

### I explain how i have config DiscordSRV:
- All the link system in managed on my Lobby server. He's the one who gives out all the awards, Discord roles...
- I have 2 two-subservers (Creative and Survival), and it is linked with same MariaDB dbb i've on the Lobby,
  - And when I try to link my account on one of its two subservers, I have a big delay (~2min) between the time I send the confirmation message for link my account, and the time when my account is considered linked

### A staff explanation:
"So what you're running into is a limitation of discordsrv not properly supporting bungeecord/velocity. There's a cache for linked users that only expires after 3 minutes pass. Since the dsrv plugin on Server A doesn't communicate with the dsrv plugin on Server B, there's no way for dsrv on Server A to tell dsrv on Server B to clear/update it's cache with the new value."

### Server software and version

 git-Purpur-2176 (MC: 1.20.4)*

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Vankka** [comment] 2024-07-07 10:47
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1492

**Closed by Vankka** 2024-07-07 10:47 UTC
Labels: bug
