### ISSUE TITLE
Ability to execute commands in console with commands in discord

### ISSUE THREAD

**Issue by MattyHD0** [DiscordSRV/DiscordSRV#667] opened 2020-03-24 03:34 UTC
Hello, I would like you to add a part in the configuration to execute commands in console with commands in discord, example:
A user run !Info on discord> make it run on console /broadcast {user} I run the command !Info

**Comment by Vankka** [comment] 2020-07-24 21:49
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/94

**Closed by Vankka** 2020-07-24 21:49 UTC
