### ISSUE TITLE
MySQL Error when loading DiscordSRV.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1391] opened 2022-04-14 20:23 UTC
### Expected behavior

No error.

### Actual behavior

```
[16:20:53] [DiscordSRV - Initialization/ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```

### Steps to reproduce

Use: https://github.com/DiscordSRV/DiscordSRV/commit/cc063da47fc0fda7b4d736bf379f61348026d858
And: MySQL 8.0.28

### Server software and version

Paper 1.18.2 Build 287

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Vankka** [comment] 2022-04-14 20:49
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1089

**Closed by Vankka** 2022-04-14 20:49 UTC
Labels: bug
