### ISSUE TITLE
Discord -> Minecraft Mentions not translating properly

### ISSUE THREAD

**Issue by DerpDerpling** [DiscordSRV/DiscordSRV#1038] opened 2021-03-02 01:31 UTC
![image](https://user-images.githubusercontent.com/57187871/109582853-e3481080-7acc-11eb-87b9-7ec3751555fb.png)
https://bin.scarsz.me/3c182030-0095-4923-a8b8-dba8f33b484b#6vFhKLptAY6Eg6UdoH8m8fEzuP14HCYC
when i ping someone without a message, it shows their name, but when i ping with a message, it shows their user id... i included an image and the debug report

**Comment by Vankka** [comment] 2021-03-03 09:26
Debug like has expired, very likely a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/935

**Comment by Scarsz** [comment] 2021-03-04 21:39
Closing due to inactivity/probably already fixed in snapshots https://snapshot.discordsrv.com

**Closed by Scarsz** 2021-03-04 21:39 UTC
