### ISSUE TITLE
Messages in messages.yml get re-enabled after version upgrade

### ISSUE THREAD

**Issue by lazaroblanc** [DiscordSRV/DiscordSRV#988] opened 2021-01-22 00:46 UTC
I've noticed this updating from 1.21.0 to 1.21.1 and 1.21.1 to 1.21.3

I have `MinecraftPlayerJoinMessage` and `MinecraftPlayerLeaveMessage` disabled and they get re-enabled after the upgrade.

**Comment by Scarsz** [comment] 2021-01-22 01:09
Duplicate of #212

**Closed by Scarsz** 2021-01-22 01:09 UTC
