### ISSUE TITLE
Cant make message from mc appear on two channels

### ISSUE THREAD

**Issue by JadenJSJ** [DiscordSRV/DiscordSRV#664] opened 2020-03-19 15:13 UTC
Cant make message from mc appear on two channels
please add it as a feature so thati can log the chat on discord and also have minceaft chat on general

**Comment by Vankka** [comment] 2020-03-19 15:22
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/111

**Closed by Vankka** 2020-03-19 15:22 UTC
Labels: duplicate
