### ISSUE TITLE
MySQL Driver shows deprecated error on startup

### ISSUE THREAD

**Issue by camarokris** [DiscordSRV/DiscordSRV#1225] opened 2021-08-14 00:15 UTC
I am seeing the following on startup only but not reload. It appears the driver class for mysql being used is deprecated. 

`[17:54:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:ticket-tools(873697807289180170)
[17:54:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:ticket-transcripts(863513865001762856)
[17:54:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:the-talk(858928590870282290)
[17:54:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console forwarding assigned to channel TC:minecraft-console(858218228673413140)
[17:54:38] [DiscordSRV - Initialization/ERROR]: [[STDERR] ] com.mysql.jdbc.Driver Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[17:54:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] JDBC tables passed validation, using JDBC account backend
[17:54:38] [Server thread/INFO]: [Geyser-Spigot] Loaded Floodgate key!
[17:54:38] [Server thread/INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
`

here is the output of /discord debug
https://bin.scarsz.me/05b7112e-7547-4188-a651-68095a6af7c4#PkxJZmQm7innjghxcNaebHg1KCAwmQAv

**Comment by Vankka** [comment] 2021-08-14 07:09
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1089

**Closed by Vankka** 2021-08-14 07:09 UTC
