### ISSUE TITLE
Loading class `com.mysql.jdbc.Driver'. This is deprecated.

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#1149] opened 2021-06-06 23:08 UTC
DiscordSRV-Build-1.23.0-SNAPSHOT-10583ff

New driver is ``com.mysql.cj.jdbc.Driver``

```
[15:06:39] [Log4j2-TF-1-AsyncLogger[AsyncContext@277050dc]-1/INFO]: [DiscordSRV] [JDA] Finished Loading!

[15:06:39] [DiscordSRV - Initialization/WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[15:06:39] [DiscordSRV - Initialization/INFO]: [DiscordSRV] JDBC tables passed validation, using JDBC account backend
[15:06:39] [pool-87-thread-1/INFO]: [DiscordSRV] This build of DiscordSRV is identical to develop. [latest public dev build]
```

**Comment by Dinty1** [comment] 2021-06-06 23:09
Duplicate of #1089

**Closed** 2021-06-06 23:10 UTC
Labels: duplicate
