### ISSUE TITLE
blocked ingame messages showing up in discord  chat

### ISSUE THREAD

**Issue by elaineandsparky** [DiscordSRV/DiscordSRV#979] opened 2021-01-16 21:23 UTC
We use grief preventions banned words feature which blocks a message from being sent in main ingame chat if it contains a listed word. However, the message is still being sent in our discord ingame channel.

Any way of stopping this?

**Comment by Vankka** [comment] 2021-01-16 21:27
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/88

**Closed by Vankka** 2021-01-16 21:27 UTC
Labels: duplicate
