### ISSUE TITLE
Ability to limit who can run !c commands by User IDs as well as Role IDs

### ISSUE THREAD

**Issue by ErrorHunter1** [DiscordSRV/DiscordSRV#1761] opened 2024-09-20 20:33 UTC
### Why?

I would like to specify the user ID instead of the role ID. Since I am not the Discord server owner, I cannot create a role that is inaccessible by everyone but myself.

### What and How?

that you can also specify userid for !c instead of just the name of the role

### Are there alternatives?

-

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by thewilloftheshadow** [comment] 2024-09-20 20:35
Where are you wanting to specify the user id?

**Comment by J-295** [comment] 2024-09-20 21:04
The option would be `DiscordChatChannelConsoleCommandRolesAllowed`

**Comment by ErrorHunter1** [comment] 2024-09-21 23:38
I don't use a Rolename or id 

I want to use a userid 

only 2 users should be able to do it but we both (2) can't take care that the owner can't give himself the rights and that's why I want to use user ID

**Comment by thewilloftheshadow** [comment] 2024-09-26 17:25
This is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1359

**Closed by thewilloftheshadow** 2024-09-26 17:25 UTC
Labels: duplicate, enhancement

**Comment by ErrorHunter1** [comment] 2024-09-26 18:30
And why hasn't it been installed long ago? It's already 3 years old, so why isn't it there yet?

**Comment by Dinty1** [comment] 2024-09-26 18:48
Because the project is maintained by a team of volunteers who don’t have the time or willpower to implement every feature that people request. It’s also open source so in theory people who really badly want something added can do it themselves/get someone else to do it.
