### ISSUE TITLE
Feature Request: TOTP-like authentication upon join

### ISSUE THREAD

**Issue by kotx** [DiscordSRV/DiscordSRV#892] opened 2020-10-26 05:21 UTC
Basically, ask the user to DM a code to the bot every time they attempt to join the server. This helps against Minecraft account hijacking and/or UUID spoofing (to bypass linking on offline-mode servers).

**Comment by Vankka** [comment] 2020-10-26 09:41
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/487

**Closed by Vankka** 2020-10-26 09:41 UTC
