### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by iBars** [DiscordSRV/DiscordSRV#586] opened 2019-12-10 19:14 UTC
1. Add placeholder to show Discord user id (`#0123`) in Minecraft chat to resolve users with equal nicknames. Because some people can use the same nickname as server admin for example
2. Trim :emoticons: from role name shown in Minecraft chat. E.g. my owner role named `👑 Project owner` and in Minecraft chat it looks as `:crown: Project owner`. Trim :emoticons: and then trim spaces { roleNameString.replaceEmoticons().trim(); }
3. Add ability to show player Permissions group prefix & suffix instead of only use of just Permissions group name

**Comment by underscore11code** [comment] 2019-12-10 19:54
> Add ability to show player Permissions group prefix & suffix instead of only use of just Permissions group name

Check out the [vault PlaceholderAPI expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#Vault). %vault_prefix% and %vault_suffix% `/papi ecloud download Vault`

**Comment by iBars** [comment] 2019-12-11 10:14
PAPI is too big plugin to install it just for DiscordSRV

**Comment by Vankka** [comment] 2019-12-12 22:13
Will probably be added in the future. Don't hold your breath though

**Comment by Vankka** [comment] 2019-12-12 22:19
1. ID..? Would make fill chat too fast. If you mean discriminator, that can be the same (with nicknames), if you have problems with pretending to be staff, use roles in the DC -> MC format and/or the ban hammer
2. Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/434
3. What I said above, Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/103

**Closed by Vankka** 2019-12-12 22:19 UTC
