### ISSUE TITLE
[messages.yml] MinecraftPlayer*Message.Enabled not transferring to new config file generated after updating versions

### ISSUE THREAD

**Issue by JONTTM** [DiscordSRV/DiscordSRV#986] opened 2021-01-22 00:18 UTC
- Set any of the following to `false` (Default is `true`) In messages.yml:
```
MinecraftPlayerJoinMessage.Enabled: false
MinecraftPlayerFirstJoinMessage.Enabled: false
MinecraftPlayerLeaveMessage.Enabled: false
MinecraftPlayerDeathMessage.Enabled: false
MinecraftPlayerAchievementMessage.Enabled: false
```

(this is the proper structure in the file)
```
MinecraftPlayerJoinMessage: 
  Enabled: false
```

- Upgrade versions (occurred for me on both 21.1 > 21.2 and 21.2 > 21.3)

What actually happens:
The `Enabled: false` is changed to `Enabled: true` in the upgraded messages.yml

What is supposed to happen:
The `Enabled: false` stays `Enabled: false` as the user set it before the upgrade

**Comment by Scarsz** [comment] 2021-01-22 00:19
Duplicate of #212

**Closed by Scarsz** 2021-01-22 00:19 UTC
