### ISSUE TITLE
DiscordSRV JDA Console Spam

### ISSUE THREAD

**Issue by Vxlt** [DiscordSRV/DiscordSRV#770] opened 2020-06-26 13:46 UTC
Hello, I am getting this whenever my server is online.

>.... [08:39:10 WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/675099909539758121

**Comment by Vankka** [comment] 2020-06-26 15:44
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/719

**Closed by Vankka** 2020-06-26 15:44 UTC
