### ISSUE TITLE
Add to Forge

### ISSUE THREAD

**Issue by jsinc-sebastian** [DiscordSRV/DiscordSRV#1561] opened 2023-07-07 20:30 UTC
### Why?

I want mods that is only for Forge, and really want support with Forge 1.20

### What and How?

It would be added to servers. It would have the same functionalty, but in Forge developement.

### Are there alternatives?

IDK, not so good at modding. But would've be good.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else
# NOTE: This is just a latest post so someone can find the other old ones. Please do not delete this!
#1496 is the original.

I think t's alright to have it. Also looked for it, but doesn't exist:
https://www.curseforge.com/minecraft/bukkit-plugins/discordsrv/screenshots

**Comment by Vankka** [comment] 2023-07-07 20:49
Duplicate of #1496

**Closed by Vankka** 2023-07-07 20:49 UTC
Labels: duplicate
