### ISSUE TITLE
Feature suggestion: Set a discord role on members currently in game

### ISSUE THREAD

**Issue by steven-archer** [DiscordSRV/DiscordSRV#501] opened 2019-07-07 11:04 UTC
Suggest synchronizing a role specifically for members currently on the Minecraft server. 

For example, a role called "PLAYING NOW!" could exist in the Discord server, and those linked players who are currently in the Minecraft server are assigned this role until they log off or the server restarts.

The idea is that you could have all your in-game members show up at the top of the member list in Discord by giving them this role, as long as the role is set up to group those members separately and is placed high in the roles hierarchy. The role itself could be set up any which way, but this is just how I imagine using it. Any number of things could be done with a role specially assigned to online players.

**Comment by Vankka** [comment] 2019-07-07 11:08
Duplicate of #268

**Closed by Vankka** 2019-07-07 11:08 UTC
