### ISSUE TITLE
Add a verification system to non-premium (cracked) servers

### ISSUE THREAD

**Issue by DuckyBlender** [DiscordSRV/DiscordSRV#1144] opened 2021-05-30 16:48 UTC
It would be very cool if you could have a non-premium server without a login plugin. Right now, I'm only allowing people that linked their account to discord and is on the private server. This works for alts, but someone could still log on someone's account. 
My suggestion is very simple to implement.

**If there is a change in the IP of a user, tell the user that he needs to send a new code to the bot to verify that this is really you on a new IP.** 

Of course, this should be in the config and disabled by default to not cause confusion. This could really change a lot of servers and finally log on servers that are non-premium without having to annoyingly /login.
Have a good day :)

**Comment by Scarsz** [comment] 2021-06-07 23:21
Duplicate of #487

I am interested in implementing this soonish though

**Closed by Scarsz** 2021-06-07 23:21 UTC
