### ISSUE TITLE
com.mysql.jdbc.Driver Loading class `com.mysql.jdbc.Driver'. This is deprecated

### ISSUE THREAD

**Issue by sphings79** [DiscordSRV/DiscordSRV#1232] opened 2021-08-24 14:38 UTC
[07:44:57] [DiscordSRV - Initialization/ERROR]: [[STDERR] ] com.mysql.jdbc.Driver Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

PaperMC 1.17.1 209

**Comment by thewilloftheshadow** [comment] 2021-08-24 14:50
Dupe of #1089

**Closed** 2021-08-24 15:49 UTC
Labels: duplicate
