### ISSUE TITLE
Console color coding.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1454] opened 2022-09-05 05:11 UTC
### Expected behavior

Convert console colors correctly.

### Actual behavior

```
    Line 17366: [01:02:37] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] Chat: [%channelcolor%Discord | Owner] andrewkm > %channelcolor%set
    Line 17369: [01:02:38] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] Chat: [%channelcolor%Discord | Owner] andrewkm > %channelcolor%set
    Line 17370: [01:02:38] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] Chat: [%channelcolor%Discord | Owner] andrewkm > %channelcolor%set
```

https://i.imgur.com/7Hd2Ide.png

TL;DR: all we want is some sanity in the console logs when we examine things. :)

### Steps to reproduce

Type from Discord to Game with color codes.

### Server software and version

Paper 1.19.2 Build 138

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

I eat 12 pillsbury cookies nearly every night and have no regrets.

**Comment by andrewkm** [comment] 2023-09-30 22:33
@Dinty1 is this something that may be considered?

**Comment by granny** [comment] 2024-08-09 05:39
Unable to reproduce on the latest release. If this is still happening to you, please create a support ticket in our discord server and i'll take a look.

**Comment by andrewkm** [comment] 2024-08-13 18:07
> Unable to reproduce on the latest release. If this is still happening to you, please create a support ticket in our discord server and i'll take a look.

Made a ticket, (19051)
Color goes through fine in game: https://i.imgur.com/eFz6WMi.png
Console however still shows `%channelcolors%`: https://i.imgur.com/BcElLKO.png

**Comment by granny** [comment] 2024-08-16 07:21
fixed in latest snapshot build. https://snapshot.discordsrv.com

**Closed** 2024-11-16 02:16 UTC
Labels: bug, fixed
