### ISSUE TITLE
Minecraft Banned role feature 

### ISSUE THREAD

**Issue by Caliy659** [DiscordSRV/DiscordSRV#1042] opened 2021-03-06 10:13 UTC
Ability to give banned players in Minecraft roles example;{Banned, Blocked} etc. Instead banning them from discord.

**Comment by Vankka** [comment] 2021-03-07 13:28
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/334

**Closed by Vankka** 2021-03-07 13:28 UTC
