### ISSUE TITLE
MySQL JDBC driver class com.mysql.jdbc.Driver is deprecated.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1685] opened 2024-05-29 16:21 UTC
### Expected behavior

No error on startup.

### Actual behavior

`[12:10:02] [DiscordSRV - Initialization/ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`

### Steps to reproduce

Paper 1.20.6 Build 115
DiscordSRV compiled against: https://github.com/DiscordSRV/DiscordSRV/commit/cfef29561f0d5224e369dc7aa2c04f175189c394
Configuration: https://pastebin.com/3RRqiRfD
MySQL: 8.0.37

### Server software and version

Paper-115 (1.20.6)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

More information upon request.

**Comment by J-295** [comment] 2024-05-29 16:34
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1678

**Closed by J-295** 2024-05-29 16:34 UTC
Labels: bug
