### ISSUE TITLE
Custom Advancement Translation

### ISSUE THREAD

**Issue by Metrocysh** [DiscordSRV/DiscordSRV#1639] opened 2024-01-31 22:39 UTC
### Why?

The plugin currently doesn't have support for some custom advancements, specifically the ones that use the Translate function for different languages, as they will show up as their raw name instead of any translation available.

For example: The advancement in chat looks like `"Player has made the advancement advancement.something.something.title!"`

### What and How?

As I would have in mind, the plugin could maybe have a new file/config that lets you add the translation you want for specific strings, like for example if my custom advancement has

```
"title":
{
	"translate": "advancements.servername.craft_bucket.title"
}
```

And in the English language from the server resourcepack, that advancement would be called Liquid Pocket.
The configuration should let you set an array like, I don't know:
```
"advancements.servername.craft_bucket.title": "Liquid Pocket"
```
Then the message would get replaced with the translation whenever a player gets the advancement! Or at least that's how I think it could work.

### Are there alternatives?

There could also be a way to add these arrays by just inputting the desired language .JSON files?
Like, adding `en_US.json` somewhere in the plugin's folder, and use every advancement translation in that file for the replacements.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment] 2024-04-13 13:01
This seems out of scope for this plugin. I feel like this would be better from a plugin that focuses around advancements messages, similar to how [DeathMessages](https://www.spigotmc.org/resources/deathmessages.3789/) gives you full customization over all death messages. If anyone knows of a plugin that does that (or decides to make their own), feel free to share.

**Closed by granny** 2024-04-13 13:01 UTC
Labels: enhancement

**Comment by Vankka** [comment] 2024-04-13 13:10
I'll correct granny's comment to say that we are going to implement something for translating advancement messages in Ascension, but I'm marking this as a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1162
