### ISSUE TITLE
Feature: Join/leave and server status message go to multiple channels rather than just the Main one

### ISSUE THREAD

**Issue by Kenix3** [DiscordSRV/DiscordSRV#456] opened 2019-05-09 16:33 UTC
Join/leave and default channel messages should be broadcast between multiple discord channels. Perhaps by allowing a configuration array as such:

Channels: {"channel1": {"main": true, "channelID": "channelID1"}, "channel2": {"main": true, "channelID": "channelID2"}}

If channel key configuration is an array, then we look for Main. If it exists then use it else default to true if this is the first channel and false otherwise.

If channel key is NOT an array, then follow current behaviour: first channel is flagged as main = true and the rest as main = false.
Channels: {"channel1": "channelID1", "channel2": "channelID2"}
would also be supported syntax

**Comment by Vankka** [comment] 2019-05-14 11:34
Duplicate of #111

**Closed by Vankka** 2019-05-14 11:34 UTC

**Comment by daniel-widrick** [comment] 2019-07-09 18:09
This got closed with no updates? This would be a great feature...

**Comment by Vankka** [comment] 2019-07-09 18:12
This is the same request as #111, and that is still open, and will be added in to a future update, most likely DiscordSRV2 (no eta when this will be added)
