### ISSUE TITLE
Add DiscordChatChannelBlockedRoles

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1282] opened 2021-10-11 03:25 UTC
### Why?

I want certain roles to be able to type in a Discord channel, but not have their message processed into the game.

### What and How?

Achieved by a new setting as such:
```
# DiscordChatChannelBlockedRoles: Discord roles that should not have their messages processed & sent to MC.
DiscordChatChannelBlockedRoles: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelBlockedRolesAsWhitelist: false
```

(The whitelist would be a nice bonus addition.)

### Are there alternatives?

Not for what I'm trying to accomplish sadly.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

N/A

**Comment by granny** [comment] 2021-10-11 03:36
duplicate of #861

**Closed by granny** 2021-10-11 03:36 UTC
Labels: enhancement
