### ISSUE TITLE
DiscordSRV api hook failing when config isn't loaded yet

### ISSUE THREAD

**Issue by BobbyMere** [DiscordSRV/DiscordSRV#572] opened 2019-11-16 09:13 UTC
The dev of Boss plugin name kangarko said to report this: `github.scarsz.discordsrv.util.LangUtil$InternalMessage.toString(LangUtil.java:816)
15.11 15:05:35 [Server] INFO java.lang.NullPointerException`

```
[15:31:23] [Server thread/INFO]: java.lang.NullPointerException
[15:31:23] [Server thread/INFO]: at github.scarsz.discordsrv.util.LangUtil$InternalMessage.toString(LangUtil.java:816)
[15:31:23] [Server thread/INFO]: at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:63)
[15:31:23] [Server thread/INFO]: at org.mineacademy.boss.lib.fo.model.LpT7$protected.<init>(SourceFile:213)
[15:31:23] [Server thread/INFO]: at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:313)
[15:31:23] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[15:31:23] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[15:31:23] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[15:31:23] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
```

to you guys

DiscordSRV loads correctly but disables boss plugin

Should I be talking to Kangarko instead?

**Comment by kangarko** [comment] 2019-11-16 09:23
I am here, just wanted to report this as well, seems like this happens when we just call the subscribe() method for DiscordSRV 1.18.1 with the object instance of the class that calls it.

**Comment by Scarsz** [comment] 2019-11-16 21:42
This looks like an issue of trying to hook into DiscordSRV before it's config is loaded. The config needs to load because that's what determines the plugin's language.

Make sure you have DiscordSRV in your `softdepend` list. You could also try scheduling a repeating task that checks until `DiscordSRV.config() != null && DiscordSRV.config().getLanguage() != null`

**Comment by BobbyMere** [comment] 2019-11-17 00:58
How how would I do that or is this targeted to Kangarko?

**Comment by pkrok01** [comment] 2019-11-17 01:14
That would be something directed to the plugin developer @kangarko

**Comment by Scarsz** [comment] 2019-11-19 04:00
fixed with https://github.com/DiscordSRV/DiscordSRV/commit/5c3c986a04a2dbf5dbea8d2c05bf2e4a45b567db, can no longer reproduce with ApiTest

**Closed by Scarsz** 2019-11-19 04:00 UTC

**Comment by kangarko** [comment] 2019-11-19 16:04
I believe many plugins are affected not just mine, so a fix in Discord was the best solution, thank you!
