### ISSUE TITLE
All messages translatable?

### ISSUE THREAD

**Issue by Patendo** [DiscordSRV/DiscordSRV#807] opened 2020-07-21 20:36 UTC
Can you add that you can change all the messages that are output in Minecraft and on Discord? Messages such as /discord unlink, /discord linked, the help page /discord help, and any messages the bot sends you on Discord?

**Comment by Vankka** [comment] 2020-07-21 20:37
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/561

**Closed by Vankka** 2020-07-21 20:37 UTC
