### ISSUE TITLE
Suggestion: Add a possibility for sending chat messages on two or more Discord servers at once.

### ISSUE THREAD

**Issue by TDFPL** [DiscordSRV/DiscordSRV#1191] opened 2021-07-07 19:42 UTC
It would a neat idea and it's weird it wasn't implemented yet.

**Comment by Dinty1** [comment] 2021-07-07 19:44
This is planned for the upcoming rewrite & has probably already been suggested somewhere

**Comment by Scarsz** [comment] 2021-07-07 19:48
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/111

**Closed** 2021-07-07 19:48 UTC
Labels: duplicate
