### ISSUE TITLE
Role/Name Enhancment

### ISSUE THREAD

**Issue by Relaxing9** [DiscordSRV/DiscordSRV#613] opened 2020-01-16 03:14 UTC
Since you can include emojis, in your name and in your role name for discord aesthetics, can you make either a placeholder which checks if there are any ':' in your name or role and marks the end of the string there, or can you add an option to disable the emoji (in my case Owner :crown:) from appearing in the game. This only occurs when writing from a Discord Chat Channel to the Server.

**Comment by Vankka** [comment] 2020-01-16 04:05
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/434 / https://github.com/DiscordSRV/DiscordSRV/issues/507

**Closed by Vankka** 2020-01-16 04:05 UTC
